color: null
fieldLayouts:
  c5e0b3a6-149d-4568-8315-f766366ad439:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: caab43fe-2f5b-47d9-bd1e-5aa549812ed3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1bfc953b-7554-4a01-8467-f1af9c7f27b4 # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e19c822-f877-412a-bb16-e810a98f46b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 052619ef-691e-459c-b037-3d9473ce1c71
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ad77603-473e-47df-a552-b8225f4da1f2
        userCondition: null
handle: accordionEntry
hasTitleField: false
icon: rectangle-history
name: 'Accordion Entry'
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
