color: amber
fieldLayouts:
  16fac39f-5345-4a2a-9f84-24043a6d30ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ca3ed283-e995-49aa-81f4-38a48762931d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d8da8b4-7e9e-46cc-a299-ed0ecf386bf8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1926103b-1789-4922-8839-a48a626cf1de
        userCondition: null
handle: alertEntry
hasTitleField: true
icon: bell
name: 'Alert Entry'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
