color: rose
fieldLayouts:
  6aaa7b6c-96d7-4b59-bec6-783988f84218:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-12T15:07:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dad71e68-b379-4afe-89fe-f311466607c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T15:12:27+00:00'
            elementCondition: null
            fieldUid: 2443cd61-2a9b-4eca-bf09-c026477c5b38 # Annual Meeting Grid
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3f42546-c47a-408f-9781-8b43c05aa31f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a2fe471c-badc-48e7-99cd-af4961ab88bf
        userCondition: null
handle: annualMeeting
hasTitleField: true
icon: null
name: 'Annual Meeting'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
