color: null
fieldLayouts:
  491a67a7-35c0-43e5-8bd3-121df799399f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-01T13:52:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bfd853f2-de3e-42c1-8080-e1633f17bfd7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-01T14:44:31+00:00'
            elementCondition: null
            fieldUid: 68dd303d-90e5-40b0-bce7-c0069a17ad01 # Rich Text (50 word limit)
            handle: null
            includeInCards: false
            instructions: null
            label: 'Blog Preview Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22e3fcca-7d6e-4d97-9566-2ab07814c23a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-11-01T13:56:06+00:00'
            elementCondition: null
            fieldUid: 94c492e6-2585-46cd-b5f7-277f35023321 # Single Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab9c5a78-46e2-49fe-a946-7ed677aeacb2
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-01T14:02:08+00:00'
            elementCondition: null
            fieldUid: f1830310-353b-4af7-a4e3-48dd1df6b8b3 # Content Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca862496-e3d5-490b-8d05-392a7106db80
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b59b3f71-0366-40b4-86ed-8e6a8f0c7510
        userCondition: null
handle: blogPreview
hasTitleField: true
icon: ''
name: 'Blog Preview'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
