color: red
fieldLayouts:
  02d5022a-db46-45c6-b360-63294235fd1f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-18T14:45:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 857adf52-e83e-469e-9845-ecad0ba8bb87
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-18T14:46:52+00:00'
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9d4f538-f9ff-4d8d-8598-be95894f7e4c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a6e32b02-d6c7-4788-a3cf-0d5a7499f471
        userCondition: null
handle: butterGraph
hasTitleField: true
icon: butter
name: 'Butter Graph'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
