color: cyan
fieldLayouts:
  1e8f2ade-e236-48ce-bd37-f7ef7991daea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-17T21:52:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4f40088d-354e-479c-990e-6dc3bac5a08f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T21:52:41+00:00'
            elementCondition: null
            fieldUid: 68dd303d-90e5-40b0-bce7-c0069a17ad01 # Rich Text (150 word limit)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db600871-dd94-4e03-85a1-f782736b1c10
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T21:52:41+00:00'
            elementCondition: null
            fieldUid: 5156b559-8221-4bea-a555-7fcf5a19d86e # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0087aa95-b890-4686-817b-0608e2d63033
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e0621e9-4206-4402-b073-a42f9f70a8e5
        userCondition: null
handle: cardEntry
hasTitleField: true
icon: address-card
name: 'Card Entry'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
