color: amber
fieldLayouts:
  1aa54cf8-4484-4264-b8d8-3715dcfd2575:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 90db9d1d-79c6-433c-b041-96021126a3f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41b72d76-53a5-4ce0-a968-96e72740dc36 # Card Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6825e26f-b14f-4de1-8236-4d7e737d2637
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8acd79d5-78a0-439a-9eca-f81b044b2469
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83d66a47-2c77-4863-bdb6-889f45538deb # Grid Toggle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5964c90c-d7d7-4aad-8a72-4c7df4b1b69a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d1d81f4-7854-47a3-ac54-9469e6834614 # Cards Per Row
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b053f54c-e232-42e4-bb4c-bd9657386e9b
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: d515db9d-5307-4703-9de7-3bdeeb844f3c
        userCondition: null
handle: cardBlock
hasTitleField: false
icon: address-card
name: 'Card Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
