color: null
fieldLayouts:
  1e8f2ade-e236-48ce-bd37-f7ef7991daea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4f40088d-354e-479c-990e-6dc3bac5a08f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fe737a8-3ccb-496d-9aac-7d838a510287
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5156b559-8221-4bea-a555-7fcf5a19d86e # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0087aa95-b890-4686-817b-0608e2d63033
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 090ed5cb-45e7-4ccb-bdad-3c90def43aa4 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63768956-3cbf-45f0-b5bd-c98b0488e6be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e0621e9-4206-4402-b073-a42f9f70a8e5
        userCondition: null
handle: cardEntry
hasTitleField: true
icon: address-card
name: 'Card Entry'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
