color: yellow
fieldLayouts:
  670fd04d-2790-4ab9-9c52-6ef91e37dbdf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-10T14:48:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 559ee797-83bf-4d48-bda6-1ecbfecc700a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T14:50:36+00:00'
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8789fb4d-329f-408b-9ee3-29a01c2843a3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T14:50:36+00:00'
            elementCondition: null
            fieldUid: 5156b559-8221-4bea-a555-7fcf5a19d86e # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40cde564-8fe3-4922-8da7-2358dd00d29d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: af980371-49ed-4acc-8b60-7143d94122d6
        userCondition: null
handle: ctaBlock
hasTitleField: true
icon: headset
name: 'CTA Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
