color: cyan
fieldLayouts:
  e01774c9-8fbe-42de-bb4c-4543e2818a94:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-17T21:51:42+00:00'
            elementCondition: null
            fieldUid: 7cbd6694-a78c-4e20-8e1f-ac1873f67859 # Number
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c17f69a-7e97-4c3f-9407-a21c8921eac3
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-17T21:51:42+00:00'
            elementCondition: null
            fieldUid: 4df2c060-563c-4f39-a89d-acc35c522841 # Short Text (20 word limit)
            handle: numberLabel
            includeInCards: false
            instructions: null
            label: 'Number Label'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39a7395e-9c44-45a6-bbbf-2beb77546d97
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-17T21:42:27+00:00'
            elementCondition: null
            fieldUid: cfcffb85-6685-433b-b38c-b9a01894b854 # Text
            handle: fact
            includeInCards: false
            instructions: null
            label: Fact
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29eb4adb-3241-4b43-b63f-058e06f08996
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 528facc8-fb3c-4463-b115-03cdc2ce441d
        userCondition: null
handle: factEntry
hasTitleField: false
icon: head-side-brain
name: 'Fact Entry'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
