color: yellow
fieldLayouts:
  2c1c537b-3638-418c-be39-5905aac6f990:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-17T21:42:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9165af9f-cf09-44c0-b725-57303632b9b9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-17T21:42:02+00:00'
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 512d492b-eb65-4088-a868-5a8d128a9736
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-17T21:42:02+00:00'
            elementCondition: null
            fieldUid: 70b3a49b-74b2-4178-b789-79e06e724ffc # Fact Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe235c55-6f10-498a-a454-e4c71d95d10f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d91774eb-ff44-4ce0-a5d8-dd9d42b7bab7
        userCondition: null
handle: factBlock
hasTitleField: true
icon: head-side-brain
name: 'Fact Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
