color: null
fieldLayouts:
  bb9b8d13-66fd-4c0a-a16d-6e8196fdb8d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cbf69eb1-59dd-4d11-a733-a873a17c414e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4afd092-7534-4676-88f9-85d9c247b62f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5156b559-8221-4bea-a555-7fcf5a19d86e # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4de3e96-b4da-46db-82a9-5ca6b5139151
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2ca01790-b3a0-4ca4-8891-7bd35a67358d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d894a0ee-7120-47c1-983b-df9c4510e5a6 # Image Array
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c415fe1-796a-4751-a539-2dff9d409f74
            userCondition: null
            warning: null
            width: 100
        name: 'Image Carousel 1'
        uid: 620a899e-b538-4bc9-8ab2-1330821b1ce9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d894a0ee-7120-47c1-983b-df9c4510e5a6 # Image Array
            handle: imageArray2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e66d685d-3e5f-46c5-b7cb-e1631a581474
            userCondition: null
            warning: null
            width: 100
        name: 'Image Carousel 2'
        uid: b72d10c0-91de-4845-992a-41d5ca31e952
        userCondition: null
handle: fancyCarousel
hasTitleField: true
icon: ''
name: 'Fancy Carousel'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
