color: red
fieldLayouts:
  107b1a6a-49e2-4b18-a8b1-ea2e3ed9b732:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-12T18:25:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a8a0bd85-75f5-4b4c-b78f-2d2c194ee3ac
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T18:27:20+00:00'
            elementCondition: null
            fieldUid: 68dd303d-90e5-40b0-bce7-c0069a17ad01 # Rich Text (50 word limit)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64cdfd8b-c108-4c9d-a22c-b1c527c493de
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T20:14:30+00:00'
            elementCondition: null
            fieldUid: 94c492e6-2585-46cd-b5f7-277f35023321 # Single Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b874394-1f1b-40f2-a340-745a93a98fd5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 989a07bf-8659-4c40-a9e2-ba825bd88d5e
        userCondition: null
handle: gridSection
hasTitleField: true
icon: null
name: 'Grid Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
