color: yellow
fieldLayouts:
  33ebdfdb-0053-4c6a-ac90-a5eed9abec64:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7c3ffcbf-9406-49c9-9069-46589de78626
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2be076f4-0ddd-449e-9cdc-edbaf71e90c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5156b559-8221-4bea-a555-7fcf5a19d86e # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e873590e-7cd2-4d5a-b5d9-e1bbbebf1d7f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bda7110e-ca4e-4a55-9e01-220b877882e9 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1126c5a-1878-4d28-813a-f0cf930bba12
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 952e4074-c63e-43c2-b298-cf10dd829e26
        userCondition: null
handle: heroBlock
hasTitleField: true
icon: mask
name: 'Hero Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
