color: cyan
fieldLayouts:
  f62bc95f-25b8-484a-a33e-8a082448c607:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-02T18:53:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d256b1e-3ea0-40b0-b559-71ff8fb30f9c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-30T21:22:56+00:00'
            elementCondition: null
            fieldUid: 94c492e6-2585-46cd-b5f7-277f35023321 # Single Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 753754cc-6cec-4dc0-aa4b-3db653a7fd63
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-02T18:53:55+00:00'
            elementCondition: null
            fieldUid: 68dd303d-90e5-40b0-bce7-c0069a17ad01 # Rich Text (50 word limit)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d53bac1-18bc-41d9-a302-1aae26f38d12
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-02T18:53:55+00:00'
            elementCondition: null
            fieldUid: 5156b559-8221-4bea-a555-7fcf5a19d86e # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c985b04e-3511-4935-8b92-7567687f677e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8759d8c2-25de-4a77-a3b9-42862c8bbe43
        userCondition: null
handle: imageCardEntry
hasTitleField: true
icon: image
name: 'Image Card Entry'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
