color: null
fieldLayouts:
  b7c3a9b5-4ec2-47d5-ad14-2d960d7f9a18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-31T18:42:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fd615040-76db-424f-b507-04c2725556fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T18:44:24+00:00'
            elementCondition: null
            fieldUid: 94c492e6-2585-46cd-b5f7-277f35023321 # Single Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cace36ea-4461-488a-83ba-cad31863c67e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90c5c26f-5df1-447c-b8a3-cb218402c589
        userCondition: null
handle: images
hasTitleField: true
icon: ''
name: Images
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
