color: amber
fieldLayouts:
  5637f577-4685-4365-9535-5ba32810dfc4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cba7f5d6-ae6c-45ba-a5db-d97679e23d32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ec7e276-7e29-49f7-8f38-66c54284cb8e # Image Card Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03874f5c-bddc-4602-92ad-8be282673caa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3d49dad9-8f9e-404d-8f3c-d9580cdb26ac
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83d66a47-2c77-4863-bdb6-889f45538deb # Grid Toggle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b78307d6-8e48-4e94-8289-14f1ec385d33
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d1d81f4-7854-47a3-ac54-9469e6834614 # Cards Per Row
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fa1e7e6-29fd-49c9-9f36-7c44b3859526
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: cb639554-c098-4fc4-a70f-579341fdd4ee
        userCondition: null
handle: imageCardBlock
hasTitleField: false
icon: image
name: 'Image Card Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
