color: yellow
fieldLayouts:
  172c429f-c8d8-4773-9718-4171cb7c8335:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f811a342-3964-4e1d-94f4-03bfc1e2cf7a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7c52fc6-3831-417a-8a60-04d28d6f66d9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 809b7984-2725-4016-bd55-1e7e668cb7aa # Alignment (Left, Right)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1736cd22-ebcb-49a0-b773-fc28743e3bd2
            userCondition: null
            warning: null
            width: 100
        name: Text
        uid: a4ab66b1-02db-44db-9c88-e12ea9553971
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Make sure you select which media you would like to use! (Image is the default).'
            type: craft\fieldlayoutelements\Tip
            uid: eaa96b0f-8d52-4d36-bcd2-f18b8b5b9ade
            userCondition: null
          -
            dismissible: false
            elementCondition: null
            style: warning
            tip: 'If you do not select an image/video, a Text Block will be rendered instead.'
            type: craft\fieldlayoutelements\Tip
            uid: e0c89cea-b327-4cd2-98b2-b9b05dff5528
            userCondition: null
          -
            elementCondition: null
            fieldUid: 42f330ea-8d32-462a-b565-473ac818c838 # Media Toggle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50e7bd7e-da44-44be-b004-b6e3604b5418
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bda7110e-ca4e-4a55-9e01-220b877882e9 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8dfd4a8e-6ebc-4454-971d-438e1c39501f
            userCondition: null
            warning: null
            width: 100
        name: Media
        uid: 510d8497-0cf0-4e0f-8fc0-f114eb7bb514
        userCondition: null
handle: mediaBlock
hasTitleField: true
icon: image
name: 'Media Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
