color: red
fieldLayouts:
  0ca55600-e126-438c-a0d4-32f5b6b63794:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-17T21:12:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ec020797-f600-4808-9057-4c9c8af5b845
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-18T14:46:23+00:00'
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8ae6f8d-2846-42e3-9d5b-7ad2e94b690c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1340fcc4-55f2-44a0-b27d-f1517e979b72
        userCondition: null
handle: milkGraph
hasTitleField: true
icon: cow
name: 'Milk Graph'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
