color: amber
fieldLayouts:
  376d8c36-9b3b-4843-837f-bae30ed1807d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e791c63c-1cff-45e0-a66d-8fe610a45381
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d894a0ee-7120-47c1-983b-df9c4510e5a6
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77b5d4d2-e5b1-48fc-af55-98d47198b5cf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9462aa3-a160-431e-8268-79878b840f46
        userCondition: null
handle: multiImageBlock
hasTitleField: false
icon: aperture
name: 'Multi Image Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
