color: amber
fieldLayouts:
  376d8c36-9b3b-4843-837f-bae30ed1807d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-17T22:33:47+00:00'
            elementCondition: null
            fieldUid: 742bde2f-c58c-4bbd-a64c-9c31c229dec6 # Image Gallery Matrix
            handle: images
            includeInCards: false
            instructions: null
            label: Images
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d91fad58-e36d-4052-9e55-45809b3fa360
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9462aa3-a160-431e-8268-79878b840f46
        userCondition: null
handle: multiImageBlock
hasTitleField: false
icon: aperture
name: 'Multi-Image Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
