color: yellow
fieldLayouts:
  35029bf3-0053-401b-81fc-10f8259a5ece:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 55413fe4-298b-4d50-a1e1-ee57926f41df
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cfcffb85-6685-433b-b38c-b9a01894b854 # Text
            handle: subtitle
            includeInCards: false
            instructions: null
            label: Subtitle
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af2213d1-fe9d-4edd-806b-30ea66ba8848
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 440a783b-3909-45ee-85c5-4871ef4c7634
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2295650a-2ec5-4efe-a6ef-5f4d6f0853d7 # Alignment (Left, Middle, Right)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d8254e8-5bc8-4080-9f04-521cc4667e2e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e325113-380c-447f-b1fc-e02b129c310c
        userCondition: null
handle: sectionHeaderBlock
hasTitleField: true
icon: head-side
name: 'Section Header'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
