color: amber
fieldLayouts:
  def6b37f-a349-48ea-8eab-8f3d5ea694e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-02T18:54:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 717944b8-e808-40bc-be3e-8a474ed76e35
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-02T18:55:54+00:00'
            elementCondition: null
            fieldUid: de86b9f0-bfb1-4249-8189-805912c70c62 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c667a0e1-2d31-4474-9047-48b526066059
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bed3869b-9d07-4b52-8153-ca5e5baaef40
        userCondition: null
handle: singleImageBlock
hasTitleField: false
icon: camera
name: 'Single Image Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
