color: emerald
fieldLayouts:
  c4021733-cb45-4b2e-a01d-ef8978b0d74c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-30T19:22:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ebbac0a-493d-4642-90c1-9fa220d1f53c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-30T19:22:08+00:00'
            elementCondition: null
            fieldUid: f1830310-353b-4af7-a4e3-48dd1df6b8b3 # Content Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67af699b-147e-4a00-9440-f2fa0bf08945
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50537173-cab9-4c25-bd90-194e5ee9d24a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-03T21:14:43+00:00'
            elementCondition: null
            fieldUid: fa10def5-d1fb-4dc1-8756-b7fa578e626e # Seo Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a109a2da-1eb4-4081-b90d-7d6be4727ab9
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 521b039f-edf8-4f8e-98fe-a7e005542fdd
        userCondition: null
handle: standardPage
hasTitleField: true
icon: file
name: 'Standard Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
