color: emerald
fieldLayouts:
  c4021733-cb45-4b2e-a01d-ef8978b0d74c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-30T19:22:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ebbac0a-493d-4642-90c1-9fa220d1f53c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-30T19:22:08+00:00'
            elementCondition: null
            fieldUid: f1830310-353b-4af7-a4e3-48dd1df6b8b3 # Content Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67af699b-147e-4a00-9440-f2fa0bf08945
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50537173-cab9-4c25-bd90-194e5ee9d24a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-04T21:51:38+00:00'
            elementCondition: null
            fieldUid: 81e966b9-1ec1-49ba-a12f-d566a491d98f # SEO Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 348bdb5e-b579-4a46-9bec-ee5d62ed2236
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-05T16:43:08+00:00'
            elementCondition: null
            fieldUid: c049360f-73ed-4cf3-9f63-34b9533c1a83 # Navbar Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73f8c840-3959-4619-8c2a-186dbdafb410
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 8501a5a5-f0c3-4c92-8b99-c0886b202a08
        userCondition: null
handle: standardPage
hasTitleField: true
icon: file
name: 'Standard Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
