color: null
fieldLayouts:
  c4021733-cb45-4b2e-a01d-ef8978b0d74c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ebbac0a-493d-4642-90c1-9fa220d1f53c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1830310-353b-4af7-a4e3-48dd1df6b8b3 # Content Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67af699b-147e-4a00-9440-f2fa0bf08945
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50537173-cab9-4c25-bd90-194e5ee9d24a
        userCondition: null
handle: standardPage
hasTitleField: true
icon: ''
name: 'Standard Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
