color: red
fieldLayouts:
  497bff93-b4a6-419f-b722-cba646c8107c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-12T15:15:47+00:00'
            elementCondition: null
            fieldUid: de86b9f0-bfb1-4249-8189-805912c70c62 # Image
            handle: image2
            includeInCards: false
            instructions: null
            label: Icon
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8afff3f1-2771-4355-88ad-7d7639790b5b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T15:15:47+00:00'
            elementCondition: null
            fieldUid: cfcffb85-6685-433b-b38c-b9a01894b854 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: Stat
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37f9cc03-202a-4cc0-8b8c-22562aaf2508
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T15:12:13+00:00'
            elementCondition: null
            fieldUid: 68dd303d-90e5-40b0-bce7-c0069a17ad01 # Rich Text (50 word limit)
            handle: null
            includeInCards: false
            instructions: null
            label: 'Body Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b6d60ba-b571-48ac-89e4-fe23a8255099
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T15:12:13+00:00'
            elementCondition: null
            fieldUid: de86b9f0-bfb1-4249-8189-805912c70c62 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a270e1a-d291-4833-8eea-2146b6dc3dff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 91a7ea9f-8b2d-4daf-b81e-beb2f838d33d
        userCondition: null
handle: statCard
hasTitleField: false
icon: null
name: 'Stat Card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
