color: yellow
fieldLayouts:
  f3877855-bbce-4805-882a-d9a40fe34487:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-06T22:28:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 044d50c3-d7a1-4826-9149-962a0654514e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-06T22:33:13+00:00'
            elementCondition: null
            fieldUid: b85698b5-b939-46e2-8781-40f80c88a024 # Tabs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 746a84b3-1624-4078-9513-e5f88e1dcfaf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-07T17:26:42+00:00'
            elementCondition: null
            fieldUid: fa5f2f7a-3e0b-43b3-97d0-d3c076f28d06 # Section Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5aaf129c-80c3-465d-9e45-5975316b92ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-07T17:26:42+00:00'
            elementCondition: null
            fieldUid: 8be379de-2386-49c6-be07-24db1825503f # Content Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1992723a-74d8-4ef4-87e9-679402abee1d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77909cda-d9a4-459d-837e-e00f0b22041e
        userCondition: null
handle: tabbedBlock
hasTitleField: true
icon: table-list
name: 'Tabbed Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
