color: lime
fieldLayouts:
  a3f0b68a-a7c6-4081-a96a-3dbb2a217887:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-06T22:30:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0210f493-7211-4728-a825-08dfe6e96089
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-06T22:36:11+00:00'
            elementCondition: null
            fieldUid: fd66754a-765a-488d-b730-a66067c0921b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd4dba05-dbac-49cd-970a-1bbb1b0ea6a1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-06T22:36:11+00:00'
            elementCondition: null
            fieldUid: 742bde2f-c58c-4bbd-a64c-9c31c229dec6 # Image Gallery Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8b6e00a-c4c7-4d64-91ad-9fb9a18bd93e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e93f9986-daca-460f-9a4a-2d33de8f9b5f
        userCondition: null
handle: tabContent
hasTitleField: true
icon: chart-simple
name: 'Tab Content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
