color: amber
fieldLayouts:
  e4ed4590-41fa-4c88-b5a6-3aff41766dd8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-31T14:54:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e0a7000b-1ba2-49c3-bc13-287db299b947
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T15:05:08+00:00'
            elementCondition: null
            fieldUid: 74e5a566-f44f-4607-8989-63304848426f # Testimonial Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e49ee41-bb7e-47fd-bca7-a147428139d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6876c5e7-b764-4caa-9cb9-5ba17770821f
        userCondition: null
handle: testimonialSlider
hasTitleField: false
icon: person-sledding
name: 'Testimonial Slider'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
