baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: dmi-dairy-farmer-voice-dashboard
primary: true
siteGroup: aeff5466-2f20-4b7d-8e4a-04dce57c9959 # craft-five-bp
sortOrder: 1
