altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f25a2fdb-9cd4-4b9a-a9bf-03789ddf1642:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e8e974ce-7b91-4faa-839d-ad7572491c45
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 090ed5cb-45e7-4ccb-bdad-3c90def43aa4 # Site Logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53ae511e-7d8d-44eb-ba14-86dd26a0d429
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75c4427f-76cb-4fe4-866f-687298af44c8
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
