altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  eba5df30-d0c8-4de3-9673-93d0d4692df7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-02T18:29:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5bbad53c-ea18-49c7-8f91-8cf38279d321
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-10-02T18:31:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: bd0707d6-571a-42ed-a10f-69f2fd736714
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dd236bd0-c1f5-45a6-b690-0048c6c835d2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-02T18:31:03+00:00'
            elementCondition: null
            fieldUid: f2aadb83-4021-4911-8584-7b580cf51162 # Original Image Transform
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ab3b082-a25b-4e76-9856-190a1759355a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-02T18:31:03+00:00'
            elementCondition: null
            fieldUid: d1abb0bf-e20e-47c3-8755-0560f17a2276 # Widescreen Image Transform
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12ea91e7-118e-444f-b009-8863faa88cbb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-02T18:31:03+00:00'
            elementCondition: null
            fieldUid: b300516a-a7e5-40e6-b9ec-4c3ea6f7d331 # Square Image Transform
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64561c41-d9aa-4a52-85ba-26240b6b83e4
            userCondition: null
            warning: null
            width: 100
        name: Transforms
        uid: 17009961-c326-494f-b79b-73f74f11fbdb
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: ''
