columnSuffix: null
handle: aspectRatio
instructions: null
name: 'Image Aspect Ratio'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Original
        -
          - value
          - original
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Landscape (16:9)'
        -
          - value
          - landscape
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - square
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
