columnSuffix: null
handle: brightness
instructions: 'Alter the brightness of the image'
name: Brightness
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 150%
        -
          - value
          - '150'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 125%
        -
          - value
          - '125'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 110%
        -
          - value
          - '110'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 100%
        -
          - value
          - '100'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 105%
        -
          - value
          - '105'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 75%
        -
          - value
          - '75'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 50%
        -
          - value
          - '50'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
