columnSuffix: null
handle: button
instructions: null
name: Button
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Button Text'
            -
              - handle
              - buttonText
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Button LInk'
            -
              - handle
              - buttonLink
            -
              - width
              - ''
            -
              - type
              - url
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'Text Color'
            -
              - handle
              - textColor
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - 'Brand Blue'
                    -
                      - value
                      - brandBlue
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Brand Grey'
                    -
                      - value
                      - brandGrey
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - White
                    -
                      - value
                      - white
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - Black
                    -
                      - value
                      - black
                    -
                      - default
                      - false
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - 'Background Color'
            -
              - handle
              - backgroundColor
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - 'Brand Blue'
                    -
                      - value
                      - brandBlue
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Brand Grey'
                    -
                      - value
                      - brandGrey
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - White
                    -
                      - value
                      - white
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Black
                    -
                      - value
                      - black
                    -
                      - default
                      - false
  defaults:
    -
      __assoc__:
        -
          - col1
          - Text
        -
          - col3
          - /
        -
          - col4
          - white
        -
          - col5
          - brandGrey
  maxRows: null
  minRows: null
  staticRows: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
