columnSuffix: null
handle: cardFields
instructions: null
name: 'Card Fields'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 9cda611f-c16d-47dc-ae75-72c3bf2bfa50 # Card Entry
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
