columnSuffix: null
handle: contentBlocks
instructions: null
name: 'Content Blocks'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - cb84b102-9d2a-44d7-9dd4-ff477f0d8e56 # Accordion Block
    - d956e446-2ce5-4a03-b31f-178d38c4e3e8 # Alert Entry
    - c02a173a-659a-474f-a8d0-d1cf4b6d7fb5 # Card Block
    - 721054c3-0bf9-4471-9b23-19a86645b4ae # Hero Block
    - 3080309c-cc07-4af0-aef6-94a96f235885 # Media Block
    - b1cff360-784e-4a8e-bf27-2683495ff975 # Rich Text Block
    - ad916db7-1501-45f0-88fe-2966c21fe1aa # Section Header
    - 7d5fd0be-4db9-45f4-990d-68b6f5ee56e4 # Fact Block
    - b02140d6-3b36-49ff-84fa-a24d268fdc67 # Image Card Block
    - 182cab13-62e2-4514-a1d4-87095afb5f85 # Single Image Block
    - 2ab67bc1-7dfc-4ea8-ba19-4399a0501f7d # Multi Image Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
