columnSuffix: null
handle: contentBlocks
instructions: null
name: 'Content Blocks'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 721054c3-0bf9-4471-9b23-19a86645b4ae # Hero Block
    -
      __assoc__:
        -
          - uid
          - 9fc539a6-3f44-4ab9-8065-1dfd72a83f75 # CTA Block
    -
      __assoc__:
        -
          - uid
          - b1cff360-784e-4a8e-bf27-2683495ff975 # Rich Text Block
    -
      __assoc__:
        -
          - uid
          - 182cab13-62e2-4514-a1d4-87095afb5f85 # Single Image Block
    -
      __assoc__:
        -
          - uid
          - db39feb2-35f0-4720-a96f-690134319792 # Tabbed Block
    -
      __assoc__:
        -
          - uid
          - 9709673b-10c4-4af1-a65f-b1accebadef6 # Spacer
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
