columnSuffix: null
handle: factFields
instructions: null
name: 'Fact Fields'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - a421d5a5-8c99-4385-931e-df852136c717 # Fact Entry
  includeTableView: false
  maxEntries: 4
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
