columnSuffix: null
handle: imageFit
instructions: "Choose how the image fits in it's container:\r\n\r\nCover: resize the image to cover the container (parts of the image that overflow will be clipped)\r\nContain: resize the image to fill the container (the image will shrink to assure the whole image is shown)\r\nFill: the image will fill the container no matter the container's aspect ratio (this will likely cause image distortion)\r\nScale Down: display the image at it's original size if possible, but scale the image to fill the container if the container becomes too small (for use with smaller images, usually)\r\nNone: display the image at it's original size no matter what (images that are larger than their container will be clipped)\r\n"
name: 'Image Fit'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Cover
        -
          - value
          - cover
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Contain
        -
          - value
          - contain
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Fill
        -
          - value
          - fill
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Scale Down'
        -
          - value
          - scaleDown
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - none
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
