columnSuffix: null
handle: imageArray
instructions: null
name: 'Image Array'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 182cab13-62e2-4514-a1d4-87095afb5f85 # Single Image Block
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
