columnSuffix: null
handle: imageGalleryMatrix
instructions: null
name: 'Image Gallery Matrix'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    - 482cb0dd-2361-49db-bb8c-232d0ee58caf # Image Entry
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
