columnSuffix: null
handle: mediaToggle
instructions: null
name: 'Media Toggle'
searchable: false
settings:
  default: false
  offLabel: 'Use Image'
  onLabel: 'Use Video'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
