columnSuffix: null
handle: sectionBackgroundColor
instructions: null
name: 'Section Background Color'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - white
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Green '
        -
          - value
          - brandGreen
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Off White'
        -
          - value
          - brandWhiteBlue
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
