columnSuffix: null
handle: testimonialMatrix
instructions: null
name: 'Testimonial Matrix'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 6e40709b-930b-437b-989e-1f072d239a51 # Quote
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
