columnSuffix: null
handle: toggle
instructions: null
name: Toggle
searchable: false
settings:
  default: false
  offLabel: 'Grid View'
  onLabel: 'Carousel View'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
