fieldLayouts:
  ac1caf37-ba90-49c3-bedd-6c8ac5bb3b17:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-23T19:22:52+00:00'
            elementCondition: null
            fieldUid: a6eaf89c-965b-42ff-ba4f-99667f42a0b0 # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ae13cf7-18db-4e08-bb5d-604a60cf0c3f
            userCondition: null
            warning: null
            width: 100
        name: 'Navigation Colors'
        uid: 43c3e89f-376d-43cd-a4ba-21ecdf511bf4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-23T19:22:52+00:00'
            elementCondition: null
            fieldUid: a6eaf89c-965b-42ff-ba4f-99667f42a0b0 # Color
            handle: color2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccbea76a-08d7-4867-9f82-635dfea23bba
            userCondition: null
            warning: null
            width: 100
        name: 'Footer Colors'
        uid: b5def709-46d7-4da5-a88b-fc67d1005645
        userCondition: null
handle: colors
name: Colors
sortOrder: 2
