defaultPlacement: end
enableVersioning: true
entryTypes:
  - dc5d1753-a61d-4d77-a754-a714afe343b3 # Blog Preview
handle: blogPosts
maxAuthors: 1
name: 'Blog Posts'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  465e8e05-dfe1-48d5-b118-10cbe924facb: # craft-five-bp
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog-posts/{slug}'
type: channel
