defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5c8911be-cceb-470a-8a6e-0c9ead9c2142 # Standard Page
handle: blogPosts
maxAuthors: 1
name: 'Blog Posts'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  465e8e05-dfe1-48d5-b118-10cbe924facb: # craft-five-bp
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog-posts/{slug}'
type: channel
